---
  - name: Host Setup | Plasmasaver
    block:
      - name: Host Setup | Plasmasaver | Install Plasmasaver
        pip:
          name: plasmasaver
        become: true
      - name: Host Setup | Plasmasaver | Save Default Profile
        shell: "plasmasaver save -e kde default"

  - name: Host Setup | PSLV Profile Downloader
    block:

      - name: Host Setup | PSLV Profile Downloader | Install
        apt:
          pkg: "megatools"
          update_cache: yes
        become: true