---
  - name: Applications | Repo Configuration
    block:
      - name: Applications | Repo Configuration | Get DEB architecture
        shell: dpkg --print-architecture
        register: deb_architecture

      - name: Applications | Repo Configuration | Add repository key
        apt_key:
          url: "{{ item.gpgurl }}"
          keyring: "{{ item.keyring }}"
          state: present
        become: true
        when: item.gpgurl is defined
        with_items: "{{ applications.repos }}"

      - name: Applications | Repo Configuration | Add repository
        apt_repository:
          repo: "{{ item.repo }}"
          filename: "{{ item.filename }}"
          state: present
        become: true
        when: item.repo is defined
        with_items: "{{ applications.repos }}"

  - name: Applications | Installation
    block:
      - name: Applications | Update | APT Existing Apps
        apt:
          upgrade: yes
          update_cache: yes
        become: true
        register: result
        until: "result is not failed"
        retries: 5
        delay: 10

      - name: Applications | Installation | APT Apps
        apt:
          pkg: "{{ applications.apps }}"
          update_cache: yes
        become: true
        register: result
        until: "result is not failed"
        retries: 5
        delay: 10

      - name: Applications | Installation | Snap Apps
        snap:
          name: "{{ item.name }}"
          classic: "{{ item.classic }}"
        become: true
        with_items: "{{ applications.snap }}"
        register: result
        until: "result is not failed"
        retries: 5
        delay: 10

      - name: Applications | Installation | Pip packages
        pip:
          name: "{{ item }}"
          state: latest
        with_items: "{{ applications.pip }}"
        register: result
        until: "result is not failed"
        retries: 5
        delay: 10

      - name: Applications | Installation | Google chrome stable
        apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        become: true
        retries: 5
        delay: 10

      - name: Applications | Installation | helmfile
        shell: |
          # install helm
          curl -fsSL -o /bin/helm-{{ applications.helm_version }}-linux-amd64.tar.gz https://get.helm.sh/helm-{{ applications.helm_version }}-linux-amd64.tar.gz
          tar xvf /bin/helm-{{ applications.helm_version }}-linux-amd64.tar.gz -C /bin/
          mv /bin/linux-amd64/helm /bin/helm
          rm -rf /bin/helm-{{ applications.helm_version }}-linux-amd64.tar.gz
          rm -rf /bin/linux-amd64/
          chmod +x /bin/helm

          # install helm plugin
          helm plugin install https://github.com/databus23/helm-diff
          helm plugin install https://github.com/jkroepke/helm-secrets --version v{{ applications.helm_secrets_version }}

          # install helmfile
          curl -o /bin/helmfile -L https://github.com/roboll/helmfile/releases/download/{{ applications.helmfile_version }}/helmfile_linux_amd64
          chmod +x /bin/helmfile
        become: true

      - name: Applications | Installation | sops plugin
        apt:
          deb: https://github.com/mozilla/sops/releases/download/v{{ applications.sops_version }}/sops_{{ applications.sops_version }}_amd64.deb
        become: true
        register: result
        until: "result is not failed"
        retries: 5
        delay: 10

      - name: Applications | Installation | helm plugins
        shell: |
          # install helm plugin
          helm plugin install https://github.com/databus23/helm-diff
          helm plugin install https://github.com/jkroepke/helm-secrets --version v{{ applications.helm_secrets_version }}
        ignore_errors: true

      - name: Applications | Installation | vagrant plugins
        shell: vagrant plugin install vagrant-disksize
        ignore_errors: true
