---
  - name: Host Setup | Cleanup System
    block:
      - name: Host Setup | Cleanup System | Remove  packages
        apt:
          pkg:
            - kubectl
            - docker
            - docker-engine
            - docker.io
            - containerd
            - runc
            - cri-o
            - cri-o-runc
          state: absent
          purge: true
          force: true
        become: true
